name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 8.1.1
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  circle_flags:
  phone_numbers_parser: ^8.1.0
  intl: ">=0.17.0 <=1.0.0"
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
